// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/proto/addressbook.proto
// Protobuf Java Version: 4.30.0

package com.kfaka.demo.protos;

public interface AddressBookOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.kfaka.demo.protos.AddressBook)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.kfaka.demo.protos.Person people = 1;</code>
   */
  java.util.List<com.kfaka.demo.protos.Person> 
      getPeopleList();
  /**
   * <code>repeated .com.kfaka.demo.protos.Person people = 1;</code>
   */
  com.kfaka.demo.protos.Person getPeople(int index);
  /**
   * <code>repeated .com.kfaka.demo.protos.Person people = 1;</code>
   */
  int getPeopleCount();
  /**
   * <code>repeated .com.kfaka.demo.protos.Person people = 1;</code>
   */
  java.util.List<? extends com.kfaka.demo.protos.PersonOrBuilder> 
      getPeopleOrBuilderList();
  /**
   * <code>repeated .com.kfaka.demo.protos.Person people = 1;</code>
   */
  com.kfaka.demo.protos.PersonOrBuilder getPeopleOrBuilder(
      int index);
}
