// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/proto/addressbook.proto
// Protobuf Java Version: 4.30.0

package com.kfaka.demo.protos;

public final class AddressBookProtos {
  private AddressBookProtos() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 0,
      /* suffix= */ "",
      AddressBookProtos.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kfaka_demo_protos_Person_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_kfaka_demo_protos_Person_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kfaka_demo_protos_Person_PhoneNumber_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_kfaka_demo_protos_Person_PhoneNumber_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kfaka_demo_protos_AddressBook_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_kfaka_demo_protos_AddressBook_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*src/main/resources/proto/addressbook.p" +
      "roto\022\025com.kfaka.demo.protos\"\275\002\n\006Person\022\014" +
      "\n\004name\030\001 \001(\t\022\n\n\002id\030\002 \001(\005\022\r\n\005email\030\003 \001(\t\022" +
      "9\n\006phones\030\004 \003(\0132).com.kfaka.demo.protos." +
      "Person.PhoneNumber\032e\n\013PhoneNumber\022\016\n\006num" +
      "ber\030\001 \001(\t\022F\n\004type\030\002 \001(\0162\'.com.kfaka.demo" +
      ".protos.Person.PhoneType:\017PHONE_TYPE_HOM" +
      "E\"h\n\tPhoneType\022\032\n\026PHONE_TYPE_UNSPECIFIED" +
      "\020\000\022\025\n\021PHONE_TYPE_MOBILE\020\001\022\023\n\017PHONE_TYPE_" +
      "HOME\020\002\022\023\n\017PHONE_TYPE_WORK\020\003\"<\n\013AddressBo" +
      "ok\022-\n\006people\030\001 \003(\0132\035.com.kfaka.demo.prot" +
      "os.PersonB,\n\025com.kfaka.demo.protosB\021Addr" +
      "essBookProtosP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_kfaka_demo_protos_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_kfaka_demo_protos_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_kfaka_demo_protos_Person_descriptor,
        new java.lang.String[] { "Name", "Id", "Email", "Phones", });
    internal_static_com_kfaka_demo_protos_Person_PhoneNumber_descriptor =
      internal_static_com_kfaka_demo_protos_Person_descriptor.getNestedTypes().get(0);
    internal_static_com_kfaka_demo_protos_Person_PhoneNumber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_kfaka_demo_protos_Person_PhoneNumber_descriptor,
        new java.lang.String[] { "Number", "Type", });
    internal_static_com_kfaka_demo_protos_AddressBook_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_kfaka_demo_protos_AddressBook_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_kfaka_demo_protos_AddressBook_descriptor,
        new java.lang.String[] { "People", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
